services:
#   big-data-mongodb:
#     # 1. Replaces 'my-custom-mongo-image'
#     image: mongo:7.0
#     # 2. Replaces '--name my-mongo'
#     container_name: big-data-mongo
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: password
#     # 3. Replaces '-v mongo_data:/data/db'
#     volumes:
#       - mongo_data:/data/db
#     ports:
#       - "27017:27017"
#     # Optional: ensure it restarts if your computer reboots
#     restart: always
#   big-data-pg:
#     image: postgres:17
#     container_name: big-data-pg
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: postgres
#     volumes:
#       # - ./db:/docker-entrypoint-initdb.d
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
  big-data-neo4j:
    # Use the official Neo4j image from Docker Hub
    image: neo4j:enterprise
    hostname: neo4j
    # container_name: neo4j_db
    restart: always
    # Set environment variables for authentication and license agreement
    environment:
      # Use "neo4j/your_password" for basic auth, or "none" for no auth (dev only)
      NEO4J_AUTH: neo4j/your_password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
    ports:
      # Expose the browser port (7474) and the Bolt port (7687) to the host
      - "7474:7474"
      - "7687:7687"
    volumes:
      # Mount volumes to persist data, logs, and plugins (adjust local paths as needed)
      - neo4j_data:/data:/data
      - neo4j_logs:/logs:/logs
      - neo4j_plugins:/plugins:/plugins
  big-data-redis:
      # Use the latest Redis image from Docker Hub
    image: redis:latest
    hostname: redis_local
    # container_name: redis
    restart: always
    # Set environment variables for authentication and license agreement
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      # Exposes the container's Redis port to the host machine.
      - "6379:6379"
    volumes:
      # Mount volumes to persist data, logs, and plugins (adjust local paths as needed)
      - redis-data:/data
    command: redis-server --appendonly yes # Enables AOF persistence
  # big-data-cassandra:
  #   image: cassandra:latest
  #   container_name: big-data-cassandra
  #   ports:
  #     - "9042:9042"
  #   environment:
  #     CASSANDRA_CLUSTER_NAME: "MyTestCluster"
  #     CASSANDRA_DC: "DC1"
  #     CASSANDRA_RACK: "RACK1"
  #   volumes:
  #     - cassandra-data:/var/lib/cassandra
  #   healthcheck:
  #     test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  spark-master:
    image: apache/spark:latest
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      # - JDK_JAVA_OPTIONS=-Djava.security.manager=allow
      # - SPARK_NO_DAEMONIZE=true
      - SPARK_MASTER_OPTS=-Djava.security.manager=allow -Dspark.plugins=org.apache.spark.sql.connect.SparkConnectPlugin
   
    ports:
      - "8080:8080" # Spark Master Web UI
      - "7077:7077" # Spark Master Port
      - "15002:15002"
    volumes:
      - ./edges_subset.tsv:/opt/spark/data/edges.tsv
    networks:
      - spark-network

  spark-worker:
    image: apache/spark:latest
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      # - SPARK_MODE=worker
      # - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_WORKER_OPTS=-Djava.security.manager=allow
      - JDK_JAVA_OPTIONS=-Djava.security.manager=allow
    depends_on:
      - spark-master
    volumes:
      - ./edges_subset.tsv:/opt/spark/data/edges.tsv
    networks:
      - spark-network

volumes:
  # mongo_data:
  # pgdata:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  redis-data:
  # cassandra-data:

networks:
  spark-network:
    driver: bridge
